DROP TABLE IF EXISTS PRODUCTS;

CREATE TABLE PRODUCTS(
PRODUCT_ID INT NOT NULL,
NAME VARCHAR(50) NOT NULL,
STOCK INT NOT NULL,
PRICE_PER_UNIT FLOAT NOT NULL
);

DROP TABLE IF EXISTS ORDERS;

CREATE TABLE ORDERS(
  ORDER_ID INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  QUANTITY INT NOT NULL,
  TOTAL_PRICE FLOAT NOT NULL
);


DROP TABLE IF EXISTS ORDERS_STATUS;

CREATE TABLE ORDERS_STATUS(
  ORDER_ID INT NOT NULL,
  STATUS  VARCHAR(25) NOT NULL
);