DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT(
PRODUCT_ID INT NOT NULL,
NAME VARCHAR(50) NOT NULL,
QUANTITY_IN_STOCK INT NOT NULL,
PRICE_PER_UNIT FLOAT NOT NULL,
PRIMARY KEY(PRODUCT_ID)
);

DROP TABLE IF EXISTS ORDERS;

CREATE TABLE ORDERS(
  ORDER_ID INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  QUANTITY INT NOT NULL,
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);


DROP TABLE IF EXISTS ORDER_STATUS;

CREATE TABLE ORDER_STATUS(
  ORDER_ID INT NOT NULL,
  STATUS  VARCHAR(25) NOT NULL,
  LAST_UPDATE DATETIME  NOT NULL
);